// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ChgpTdsnQKmhpEOG-YHJFBs03ihwMRQ',
    appId: '1:711659000503:web:d928133e97e51531063332',
    messagingSenderId: '711659000503',
    projectId: 'vizzapp-8b71e',
    authDomain: 'vizzapp-8b71e.firebaseapp.com',
    storageBucket: 'vizzapp-8b71e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBect3OdsHOInHRreZKcyzF8PCrI3rK9fU',
    appId: '1:711659000503:android:39d078e0bc54b135063332',
    messagingSenderId: '711659000503',
    projectId: 'vizzapp-8b71e',
    storageBucket: 'vizzapp-8b71e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDIMWN8brcW-uxttzW-knHLdhU2MIhfE',
    appId: '1:711659000503:ios:625567a2e678e909063332',
    messagingSenderId: '711659000503',
    projectId: 'vizzapp-8b71e',
    storageBucket: 'vizzapp-8b71e.firebasestorage.app',
    iosBundleId: 'com.example.vizzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbDIMWN8brcW-uxttzW-knHLdhU2MIhfE',
    appId: '1:711659000503:ios:625567a2e678e909063332',
    messagingSenderId: '711659000503',
    projectId: 'vizzapp-8b71e',
    storageBucket: 'vizzapp-8b71e.firebasestorage.app',
    iosBundleId: 'com.example.vizzapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1ChgpTdsnQKmhpEOG-YHJFBs03ihwMRQ',
    appId: '1:711659000503:web:454f396233a94b5d063332',
    messagingSenderId: '711659000503',
    projectId: 'vizzapp-8b71e',
    authDomain: 'vizzapp-8b71e.firebaseapp.com',
    storageBucket: 'vizzapp-8b71e.firebasestorage.app',
  );
}
